[package]
name = "marlea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marlea_engine = { version = "0.1.0", path = "src/marlea_engine" }
structopt = "0.3"
